//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenShot_Grab.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenShot_Grab.Resources.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка захвата изображения!.
        /// </summary>
        internal static string capture_err {
            get {
                return ResourceManager.GetString("capture_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Буфер обмена не содержит изображение!.
        /// </summary>
        internal static string clipboard_err {
            get {
                return ResourceManager.GetString("clipboard_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка захвата изображения.
        /// </summary>
        internal static string event_capture_err {
            get {
                return ResourceManager.GetString("event_capture_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставка изображения из буфера.
        /// </summary>
        internal static string event_clipboard {
            get {
                return ResourceManager.GetString("event_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка вставки изображения из буфера.
        /// </summary>
        internal static string event_clipboard_err {
            get {
                return ResourceManager.GetString("event_clipboard_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрытие программы.
        /// </summary>
        internal static string event_close {
            get {
                return ResourceManager.GetString("event_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск редактора изображения.
        /// </summary>
        internal static string event_edit {
            get {
                return ResourceManager.GetString("event_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка запуска редактора.
        /// </summary>
        internal static string event_edit_err {
            get {
                return ResourceManager.GetString("event_edit_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Захвачен скриншот экрана.
        /// </summary>
        internal static string event_grab {
            get {
                return ResourceManager.GetString("event_grab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Захвачен скришот части экрана.
        /// </summary>
        internal static string event_grabc {
            get {
                return ResourceManager.GetString("event_grabc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Захвачен скриншот программы.
        /// </summary>
        internal static string event_grabw {
            get {
                return ResourceManager.GetString("event_grabw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление файла.
        /// </summary>
        internal static string event_removefile {
            get {
                return ResourceManager.GetString("event_removefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при удалении файла.
        /// </summary>
        internal static string event_removefile_err {
            get {
                return ResourceManager.GetString("event_removefile_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление изображения.
        /// </summary>
        internal static string event_removeimg {
            get {
                return ResourceManager.GetString("event_removeimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при удалении изображения.
        /// </summary>
        internal static string event_removeimg_err {
            get {
                return ResourceManager.GetString("event_removeimg_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение файла.
        /// </summary>
        internal static string event_save {
            get {
                return ResourceManager.GetString("event_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка сохранения файла.
        /// </summary>
        internal static string event_save_err {
            get {
                return ResourceManager.GetString("event_save_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск программы.
        /// </summary>
        internal static string event_start {
            get {
                return ResourceManager.GetString("event_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка файла на сервер.
        /// </summary>
        internal static string event_upload {
            get {
                return ResourceManager.GetString("event_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузки файла на сервер.
        /// </summary>
        internal static string event_upload_err {
            get {
                return ResourceManager.GetString("event_upload_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка сохранения файла..
        /// </summary>
        internal static string file_err {
            get {
                return ResourceManager.GetString("file_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл не найден!.
        /// </summary>
        internal static string file_nf {
            get {
                return ResourceManager.GetString("file_nf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть.
        /// </summary>
        internal static string hide {
            get {
                return ResourceManager.GetString("hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка удаления изображения..
        /// </summary>
        internal static string img_rm_err {
            get {
                return ResourceManager.GetString("img_rm_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привязать аккаунт.
        /// </summary>
        internal static string link_acc {
            get {
                return ResourceManager.GetString("link_acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to активна,.
        /// </summary>
        internal static string link_acc_status {
            get {
                return ResourceManager.GetString("link_acc_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отсуствует..
        /// </summary>
        internal static string noacc {
            get {
                return ResourceManager.GetString("noacc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат не содержит изображение!.
        /// </summary>
        internal static string noprtscr {
            get {
                return ResourceManager.GetString("noprtscr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь не найден!.
        /// </summary>
        internal static string path_nf {
            get {
                return ResourceManager.GetString("path_nf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другая копия программы уже открыта!.
        /// </summary>
        internal static string running {
            get {
                return ResourceManager.GetString("running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать.
        /// </summary>
        internal static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серверная ошибка..
        /// </summary>
        internal static string sv_err {
            get {
                return ResourceManager.GetString("sv_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отвязать аккаунт.
        /// </summary>
        internal static string unlink_acc {
            get {
                return ResourceManager.GetString("unlink_acc", resourceCulture);
            }
        }
    }
}
